### ISSUE TITLE
Application Insights

### ISSUE THREAD

**Issue by safari137** [Azure/reddog-containerapps#30]
I am trying to get application insights to create an architecture diagram.  However, so far, no data seems to go into application insights.

My bicep deployment successfully deploys.  I see the environment, I see application insights and I can see the apps are running as expected.

```
resource appInsights 'Microsoft.Insights/components@2020-02-02-preview' = {
  name: environment_name
  location: location
  kind: 'web'
  properties: { 
    Application_Type: 'web'
    WorkspaceResourceId: logAnalyticsWorkspace.id
  }
}

resource environment 'Microsoft.App/managedEnvironments@2022-03-01' = {
  name: environment_name
  location: location  
  properties: {
    vnetConfiguration: {
      internal: false
      infrastructureSubnetId: subnetId
    }
    daprAIInstrumentationKey: appInsights.properties.InstrumentationKey
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: logAnalyticsWorkspace.properties.customerId
        sharedKey: logAnalyticsWorkspace.listKeys().primarySharedKey
      }
    }  
  }
```

**Comment by safari137** [comment]
I found a work around for doing this as
`APPLICATIONINSIGHTS_CONNECTION_STRING`

I'm still curious how one could achieve setting up a nested property though.

**Comment by git2g** [comment]
Could you ensure your time range is accurately set without any filters, at which point, you should expect to see something akin to the below screenshot (after waiting for an hour or so post accessing the UI). If that's still not the case, please post your screenshot and try https://docs.microsoft.com/en-us/azure/azure-monitor/app/app-map?tabs=net#troubleshooting guide for any additional pointers.
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/18152044/178344255-41ca765b-9489-4f9c-99c0-783f2db65340.png">
