### ISSUE TITLE
Env variable name 'reddog-sql' contains invalid character, allowed characters are 'a-z, A-Z, 0-9 and _'

### ISSUE THREAD

**Issue by chhtw** [Azure/reddog-containerapps#32]
az deployment group create -n reddog -g $RG -f ./deploy/bicep/main.bicep

 throw exception as below. it happened in Cloud shell and WSL-Ubuntu 

```


{"code": "InvalidTemplateDeployment", "message": "The template deployment 'reddog' is not valid according to the validation procedure. The tracking id is '690f36b8-d93e-4a3a-bfe7-9df61acfdba0'. See inner errors for details."}

Inner Errors:
{"code": "ValidationForMultipleResourcesFailed", "message": "Validation failed for multiple resources. Check 'Error.Details[]' for more information."}

Inner Errors:
{"code": "ContainerAppInvalidEnvVarName", "message": "Env variable name 'reddog-sql' contains invalid character, allowed characters are 'a-z, A-Z, 0-9 and _'"}

Inner Errors:
{"code": "ContainerAppInvalidEnvVarName", "message": "Env variable name 'reddog-sql' contains invalid character, allowed characters are 'a-z, A-Z, 0-9 and _'"}
```

Environment:
az bicep version:Bicep CLI version 0.8.9 (33a85174de)
Az version: 
{
  "azure-cli": "2.38.0",
  "azure-cli-core": "2.38.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.87",
    "containerapp": "0.3.7",
    "k8s-configuration": "1.5.1",
    "k8s-extension": "1.2.3",
    "log-analytics": "0.2.2"
  }
}

**Comment by alicejgibbons** [comment]
Hey @chhtw, I believe a fix for this was pushed as I have it deployed in EU2 but remember running into this issue in the past. Can you try again and reopen this issue if it persists? 

For reference: az version
{
 {
  "azure-cli": "2.39.0",
  "azure-cli-core": "2.39.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.93",
    "application-insights": "0.1.16",
    "connectedk8s": "1.2.11",
    "containerapp": "0.3.8",
    "k8s-configuration": "1.6.0",
    "k8s-extension": "1.2.6"
  }
}
